//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.NET.data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbRepository : DbContext
    {
        public DbRepository()
            : base("name=DbRepository")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Catedre> Catedres { get; set; }
        public virtual DbSet<grupa> grupas { get; set; }
        public virtual DbSet<localit> localits { get; set; }
        public virtual DbSet<notele> noteles { get; set; }
        public virtual DbSet<objstgr> objstgrs { get; set; }
        public virtual DbSet<objstud> objstuds { get; set; }
        public virtual DbSet<profesor> profesors { get; set; }
        public virtual DbSet<raion> raions { get; set; }
        public virtual DbSet<spec> specs { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<v_catedre> v_catedre { get; set; }
        public virtual DbSet<v_Localit> v_Localit { get; set; }
        public virtual DbSet<v_Objstud> v_Objstud { get; set; }
    }
}
