//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.NET.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class notele
    {
        public int idnotele { get; set; }
        public Nullable<int> idstudent { get; set; }
        public Nullable<int> idobjstud { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<decimal> nota { get; set; }
    
        public virtual objstud objstud { get; set; }
        public virtual student student { get; set; }
    }
}
