//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.NET.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class objstgr
    {
        public int idobjstgr { get; set; }
        public Nullable<int> idgrupa { get; set; }
        public Nullable<int> idobjstud { get; set; }
        public Nullable<int> idprofesor { get; set; }
    
        public virtual grupa grupa { get; set; }
        public virtual objstud objstud { get; set; }
        public virtual profesor profesor { get; set; }
    }
}
