//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.NET.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public student()
        {
            this.noteles = new HashSet<notele>();
        }
    
        public int idstudent { get; set; }
        public string nmstud { get; set; }
        public string prenstud { get; set; }
        public string patrstud { get; set; }
        public string sexstud { get; set; }
        public string Ncarnet { get; set; }
        public Nullable<System.DateTime> DataNs { get; set; }
        public string GSM { get; set; }
        public Nullable<int> idgrupa { get; set; }
        public Nullable<int> idlocalit { get; set; }
    
        public virtual grupa grupa { get; set; }
        public virtual localit localit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<notele> noteles { get; set; }
    }
}
