//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.NET.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_catedre
    {
        public int idcatedre { get; set; }
        public string nmcatedre { get; set; }
        public Nullable<int> idprofesor { get; set; }
        public string nmprofesor { get; set; }
    }
}
