//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace College.NET.data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Localit
    {
        public int idlocalit { get; set; }
        public string nmlocalit { get; set; }
        public Nullable<int> idraion { get; set; }
        public string nmraion { get; set; }
    }
}
